src/padres/urls.py
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.conf.urls.defaults import *

urlpatterns = patterns('padres.views',
	url(r'^$', 										    'padresIndex', name='padres_root'),
	url(r'^informacion-personal/$', 					'padresInfo', name='padres_personal_info'),
	url(r'^cuenta/$', 									'padresCuenta', name='padres_cuenta'),
	url(r'^actualiza-informacion-personal/$', 		    'updatePadresInfo', name='padres_actualiza_info'),
	url(r'^(?P<tipo_falta>(faltas\w*|retrasos))/$',     'listaFaltas', name='padres_faltas'),
	url(r'^(?P<hijo_id>\d+)/$(?P<tipo_falta>(faltas\w*|retrasos))/', 'listaFaltasHijo', name= 'padres_faltas_hijo'),
	url(r'^ausencias/$', 								'listaAusencias', name='padres_ausencias'),
	url(r'^ausencias/(?P<hijo_id>\d+)/$', 				'listaAusencias', name='padres_ausencias_hijo'),
	url(r'^citas/$',									'citasPadres', name='padres_cita'),
	url(r'^iCalendar/Akademic.ics$',					'getiCalendar', name='padres_icalendar'),
	url(r'^comentarios/$',								'comentarios', name='padres_comentarios'),
	url(r'^comentarios/(?P<comm_id>(\d+))/$',			'comentarios', name='padres_comentario'),
	url(r'^listaCalificaciones/$',						'listaCalificaciones', name='padres_calificaciones'),
	url(r'^boletin/$',									'boletin', name='padres_boletin'),
    url(r'^files/$',                                    'get_files', name='padres_files'),
    url(r'^send/(?P<file_id>\d+)/$',                    'send_file', name='padres_send_file'),
)

src/urls.py
# -*- encoding: utf-8 -*-
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
import authority

admin.autodiscover()
authority.autodiscover()

if settings.MAINTENANCE:
    akademic_patterns = patterns('',
        (r'^admin/',             include(admin.site.urls)),
        (r'',          'docencia.views.work_in_progress'), 
    )
else:
    akademic_patterns = patterns('',
        (r'^$',                 'docencia.views.akademicLogin'),
        url(r'^accounts/login/$',  'docencia.views.akademicLogin', name='login'),
        url(r'^accounts/logout/$', 'docencia.views.akademicLogout', name='logout'),
        (r'^akademic/',          include('docencia.urls')),
        (r'^admin/',             include(admin.site.urls)),
        (r'^incidencias/',       include('incidencias.urls')),
        (r'^recursos/',          include('recursos.urls')),
        (r'^conector/',          include('conector.urls')),
        (r'^padres/',            include('padres.urls')),
        (r'^pas/',               include('pas.urls')),
        (r'^authority/',         include('authority.urls')),
        # Sólo en modo de desarrollo.
        (r'^site-media/(.*)$',  'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

cleaned_site_location = settings.SITE_LOCATION.lstrip('/')
if cleaned_site_location != "": cleaned_site_location += "/"

urlpatterns = patterns('',
    (cleaned_site_location, include(akademic_patterns)),
)

src/docencia/forms.py
# -*- coding: utf-8 -*-
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django import forms
from django.forms.widgets import SelectMultiple, CheckboxInput, Select 
from django.forms.widgets import CheckboxSelectMultiple, HiddenInput
from django.forms.extras.widgets import SelectDateWidget
from django.forms.util import ValidationError
from django.utils.dates import MONTHS
from django.utils.encoding import force_unicode
from django.utils.html import conditional_escape
from django.utils.safestring import mark_safe
from django.conf import settings

from itertools import chain
from django.forms.widgets import CheckboxInput 

from auxFunctions import getFechaRange, checkIsProfesor, isDirector, isJefeEstudios, isCoordinador
from customExceptions import UnauthorizedAccess

from notificacion.constants import *

import datetime
import re
from constants import *
from models import GrupoAula, Nivel, Ciclo, Profesor, JefeEstudios, CoordinadorCiclo, DiaEspecial, FileAttach

RE_DATE = re.compile(r'(\d{4})-(\d\d?)-(\d\d?)$')
FILE_EXT = ['jpeg', 'jpg', 'doc', 'xdoc', 'odt', 'pdf']

from auxmodels import OPCIONES_MESES
    
def get_today():
    return datetime.date.today()

def choices_anuales():
    rango = range(settings.CURSO_ESCOLAR_ACTUAL - 2, settings.CURSO_ESCOLAR_ACTUAL + 3)
    salida = []
    for item in rango:
        salida.append((item, item) )
    return salida

class DynamicForm(forms.Form):
    """
       Formulario dinamico
    """
    def setFields(self, kwds):
        """
           Set the fields in the form.
        """
        keys = kwds.keys()
        #keys.sort()
        for k in keys:
            self.fields[k] = kwds[k]

    def setData(self, kwds):
        """
           Set the data to include in the form
        """
        keys = kwds.keys()
        #keys.sort()
        for k in keys:
            self.data[k] = kwds[k]
        self.is_bound = True
    
    def print_fields(self):
        for key, field in self.fields.iteritems():
            k =  str(key) + ": " + str(field)
    
    def validate(self, post):
        """
        Validate the contents of the form
        """
        for name,field in self.fields.items():
            try:
                field.clean(post[name])
            except ValidationError, e:
                self.errors[name] = e.messages
                
class AsignaturasForm(DynamicForm):
    tipo = forms.CharField(initial='asignaturas', required=True, 
                           show_hidden_initial=False, widget=forms.HiddenInput)
    legend = 'Seleccione al menos una asignatura'
    
    def __init__(self, *args, **kwargs):
        try:
            profesor = kwargs['profesor']
            del kwargs['profesor']
        except KeyError:
            pass
        
        super(DynamicForm, self).__init__(*args, **kwargs)
        if profesor:
            self.set_asignaturas_de_profesor(profesor)
            
    def set_asignaturas_de_profesor(self, profesor):
        kwargs = {}
        for tupla in profesor.getAsignaturas():            
            label = unicode(tupla['asignatura']) + ' - ' + unicode(tupla['grupo'])
            key = str(tupla['asignatura'].id) + '@' + str(tupla['grupo'].id)
            self.fields[key] = forms.BooleanField(label=label)
            
class AlumnosCheckboxForm(DynamicForm):
    tipo = forms.CharField(initial='alumnos', required=True, 
                           show_hidden_initial=False, widget=forms.HiddenInput)
    legend = 'Seleccione al menos un alumno'
    
    def __init__(self, *args, **kwargs):
        if kwargs.has_key('lista_alumnos'):
            lista_alumnos = kwargs['lista_alumnos']            
            del kwargs['lista_alumnos']
        
        if kwargs.has_key('legend'):
            self.legend = kwargs['legend']
            del kwargs['legend']
        
        super(DynamicForm, self).__init__(*args, **kwargs)        
        if lista_alumnos:
            self.set_alumnos_from_lista_alumnos(lista_alumnos)    
            
    def set_alumnos_from_lista_alumnos(self, lista_alumnos):
        kwargs = {}
        for alumno in lista_alumnos.order_by('persona__apellidos', 'persona__nombre'):
            label = '<span class="nombre">' +  alumno.persona.nombre + '</span> <span class="apellido">' + alumno.persona.apellidos + '</span>'
            key = alumno.id
            self.fields[key] = forms.BooleanField(label=label)
            
class BaseCheckboxForm(DynamicForm):
    tipo = forms.CharField(initial='base', required=True, 
                           show_hidden_initial=False, 
                           widget=forms.HiddenInput)
    legend = 'base'
    lista = None
    def __init__(self, *args, **kwargs):
        nuevo_tipo = None
        if kwargs.has_key('lista'):
            self.lista = kwargs['lista']            
            del kwargs['lista']        
        if kwargs.has_key('legend'):
            self.legend = kwargs['legend']
            del kwargs['legend']            
        if kwargs.has_key('tipo'):
            #form.fields['tipo'].initial = kwargs['tipo']
            #self.tipo.initial = kwargs['tipo']
            nuevo_tipo = kwargs['tipo']
            del kwargs['tipo']
        
        super(DynamicForm, self).__init__(*args, **kwargs)
        
        if nuevo_tipo:
            self.fields['tipo'].initial = nuevo_tipo                
        if self.lista:
            self.set_fields_from_lista(self.lista)
            
    def set_fields_from_lista(self, lista):
        for item in lista:
            try:
                label = '<span class="nombre">' + item.persona.nombre + '</span> <span class="apellido">' + item.persona.apellidos + '</span>'
            except AttributeError:
                label = str(item)
            key = item.id
            self.fields[key] = forms.BooleanField(label=label)
            
class LoginForm(forms.Form):
    usuario = forms.CharField(max_length=200)
    password = forms.CharField(max_length=200, widget=forms.PasswordInput)

class MyCheckBoxMultiple(SelectMultiple):
    '''
        
    '''
    def render(self, name, value, attrs=None, choices=()):
        if value is None: value = []
        has_id = attrs and 'id' in attrs
        final_attrs = self.build_attrs(attrs, name=name)
        output = []
        # Normalize to strings
        str_values = set([force_unicode(v) for v in value])
        for i, (option_value, option_label) in enumerate(chain(self.choices, choices)):
            # If an ID attribute was given, add a numeric index as a suffix,
            # so that the checkboxes don't all have the same ID attribute.
            if has_id:
                final_attrs = dict(final_attrs, id='%s_%s' % (attrs['id'], i))
                label_for = u' for="%s"' % final_attrs['id']
            else:
                label_for = ''

            cb = CheckboxInput(final_attrs, check_test=lambda value: value in str_values)
            option_value = force_unicode(option_value)  
            # Obtenemos el HTML del widget
            rendered_cb = cb.render(name, option_value)
            if str_values.intersection([u'JE']) and option_value != 'JE':
                # Calculamos la subcadena antes del cierre del tag (' >')
                n = len(rendered_cb) - 3
                # Añadimos disabled al tag
                rendered_cb = rendered_cb[:n] + " disabled" + rendered_cb[n:]

            # totales es una lista de enteros con el resumen de las faltas del día
            if len(self.totales) > i:
                cad = u'<td>%s(%d)</td>' % (rendered_cb, self.totales[i])
            else:
                cad = u'<td>%s</td>' % rendered_cb

            output.append(cad)
        return mark_safe(u'\n'.join(output))

    def id_for_label(self, id_):
        # See the comment for RadioSelect.id_for_label()
        if id_:
            id_ += '_0'
        return id_
    id_for_label = classmethod(id_for_label)

class FechaMensualAnualForm(forms.Form):
    mes = forms.ChoiceField(choices=OPCIONES_MESES)
    anyo = forms.ChoiceField(choices=choices_anuales())

class SelectFechaWidget(SelectDateWidget):
    def render(self, name, value, attrs=None):
        try:
            year_val, month_val, day_val = value.year, value.month, value.day
        except AttributeError:
            year_val = month_val = day_val = None
            if isinstance(value, basestring):
                match = RE_DATE.match(value)
                if match:
                    year_val, month_val, day_val = [int(v) for v in match.groups()]

        output = []

        if 'id' in self.attrs:
            id_ = self.attrs['id']
        else:
            id_ = 'id_%s' % name

        local_attrs = self.build_attrs(id=self.month_field % id_)


        day_choices = [(i, i) for i in range(1, 32)]
        if not (self.required and value):
            day_choices.insert(0, self.none_value)
        local_attrs['id'] = self.day_field % id_
        s = Select(choices=day_choices)
        select_html = s.render(self.day_field % name, day_val, local_attrs)
        output.append(select_html)

        month_choices = MONTHS.items()
        if not (self.required and value):

src/padres/forms.py
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django import forms
from addressbook.models import PersonaPerfil, Contacto

class PadreInfoForm(forms.Form):

    nombre = forms.CharField(max_length = 50, required = True)
    apellidos = forms.CharField(max_length = 100, required = True)
    
    casa = forms.CharField(label = u'Telefono casa', max_length = 15, required = False)
    movil = forms.CharField(label = u'Telefono movil', max_length = 15, required = False)
    trabajo = forms.CharField(label = u'Telefono trabajo', max_length = 15, required = False)
    fax = forms.CharField(label = u'Numero de fax', max_length = 15, required = False)
    email = forms.EmailField(label = 'Email',  max_length = 50, required = False)

    def __init__(self, *args, **kwargs):
        super(PadreInfoForm, self).__init__(*args, **kwargs)
        for k in self.fields.keys():
            self.fields[k].widget.attrs['readonly'] = True

class PadrePassword(forms.Form):
    
    old_pass = forms.CharField(max_length = 100, widget = forms.PasswordInput, label = u'Password actual')
    new_pass = forms.CharField(max_length = 100, widget = forms.PasswordInput, label= u"Nuevo password:")
    new_pass2 = forms.CharField(max_length = 100, widget = forms.PasswordInput, label= u"Repita password")
    
    def __init__(self, *args, **kwargs):
        super(PadrePassword, self).__init__(*args, **kwargs)

    def clean(self):
        data = self.cleaned_data
        if 'new_pass' in data and 'new_pass2' in data and data['new_pass'] == data['new_pass2']:
            return data
        raise forms.ValidationError(u"Ha repetido la contrasena mal, vuelta a escribirla")

src/padres/templates/padres/ausencias.html
{% extends "padres/base.html" %}
{% load i18n %}
{% load emoticon %}

{% comment %}
{% block advertencia %}{% endblock %}
{% endcomment %}

{% block breadcrumb %}
	{{ nombre }}
{% endblock %}


{% block body %}

<h1>{{ nombre }}</h1>

{% if hijos  %}
	{% ifnotequal numHijos 1 %}
	Ver ausencias de:
	<form method="post">
		<select name="alumno_id">
				<option value="0">Todos</option>
			{% for h in hijos %}
				<option value="{{ h.hijo.id }}">{{ h.hijo }}</option>
			{% endfor %}
		</select>
		<input type="submit" value="Aceptar"/>
	</form>
	{% endifnotequal %}
	{% if filtrado %}
		<a href="./">Mostrar todos</a>
	{% endif %}

{% for h in hijos %}
	<table width="100%" id="faltas">
		<tr class="encabezado">
			<th class="encabezado" align="left" colspan="4">
				{{ h.hijo }}
			</th>
		</tr>
		{% if h.faltas %}
		<tr>
			<th>Número</th>
			<th>Inicio</th>
			<th>Fin</th>
		</tr>
		{% else %}
		<tr>
			<td colspan="4">No hay ausencias</td>
		</tr>
		{% endif %}
	{% for f in h.faltas %}
		<tr class="{% cycle odd,even %}">
			<td>{{ forloop.counter}}</td>
			<td>{{ f.inicio }}</td>
			<td>{{ f.fin }} </td>
		</tr>
	{% endfor %}
	</table>
	<br/>
{% endfor %}

{% else %}
	No se le ha asignado ninguna falta
{% endif %}


{% endblock %}

src/padres/templates/padres/base.html
{% extends "akademic/simplex4/index.html" %}
{% load i18n %}
{% load emoticon %}

{% block submenu %}
<ul>
	<li>- <a href="{% url padres_faltas 'faltas' %}">Asistencia</a></li>
	<li>- <a href="{% url padres_faltas 'retrasos' %}">Retrasos</a></li>

	<li>- <a href="{% url padres_faltas 'faltasComportamientos' %}">{{ hijos|animo }}</a></li>
	<li>- <a href="{% url padres_faltas 'faltasTarea' %}">{{ hijos|comio }}</a></li>
	<li>- <a href="{% url padres_faltas 'faltasMaterial' %}">{{ hijos|trabajo }}</a></li>
	<li>- <a href="{% url padres_ausencias %}">Ausencias</a></li>
	<li>- <a href="{% url padres_calificaciones %}">Calificaciones</a></li>
</ul>
{% endblock %}

{% block mainmenu %}
	<a href="{% url padres_root %}">Inicio</a>
	<a href="{% url padres_faltas 'faltas' %}">Mis hijos</a>
    {% comment %}
        <!-- Descomentar para facilitar la vista de citas con los profesores --> 
	    <a href="{% url padres_cita %}">Citas</a>
    {% endcomment %}
	<a href="{% url padres_comentarios %}">Comentarios</a>
	<a href="{% url padres_actualiza_info %}">Datos personales</a>
	<a href="{% url padres_cuenta %}">Mi cuenta</a>
    {% comment %}
        <!-- DESCOMENTAR PARA FACILITAR LA VISTA DE ARCHIVOS ENVIADOS POR LOS PROFESORES -->
        <a href="{% url padres_files %}">Archivos{% if user.get_profile.padre.has_files_left %} <img src="{{ MEDIA_URL }}/imgs/bookmark.gif"/>{% endif %}</a>
    {% endcomment %}
	<a href="{% url logout %}">Salir</a>
{% endblock %}

src/padres/templates/padres/bloque-calificaciones.html
{% load emoticon %}

{% for h in hijos %}
	<table width="100%" id="faltas">
		<tr class="encabezado">
			<th class="encabezado" align="left" colspan="{{ h|columna }}">
				{{ h.hijo }}
			</th>
		</tr>
		{% if not h.evaluaciones %}
			<tr>
				<td colspan="{{ h|columna }}">No hay calificaciones</td>
			</tr>
		{% endif %}
	    {% for eval in h.evaluaciones %}
		    {% if eval.calificaciones %}
		    <tr>
			    <th>Evaluación: {{ eval.evaluacion.nombre }}-{{ eval.evaluacion.cursoEscolar }}</th>
		    </tr>
		    <tr>
			    <th>Materia</th>
			    <th>Nota</th>
			    <th>Observaciones</th>
                <!--
                <th>Conceptos</th>
                <th>Procedimientos</th>
                <th>Actitud</th>
                -->
			    {{ h|header:"header" }}
		    </tr>
		    {% for cal in eval.calificaciones %}
		    <tr class="{% cycle odd,even %}">
			    <td>{{ cal.matricula.asignatura }}</td>
			    <td>{{ cal.nota|notaTextual }}</td>
			    <td>
				    {% if not cal.comentario %}
					    --
				    {% else %}
					    {{ cal.comentario }} 
				    {% endif %}
			    </td>
                <!--
                <td>{{ cal.conceptos }} </td>
                <td>{{ cal.procedimientos }} </td>
                <td>{{ cal.actitud }} </td>
                -->
            </tr>
		    {% endfor %}
		    {% if eval.informe %}
		    <tr>
			    <td colspan="3">
			        <p>
				        Informe personalizado:
			        </p>
			        {{ eval.informe.informeCompetencias|linebreaks }}
			    </td>
		    </tr>
		    {% endif %}
            <tr>
                <td colspan="3">
                    <a href="{% url padres_boletin %}?alumno={{h.hijo.id}}&evaluacion={{eval.evaluacion.id}}">Ver boletín</a>
                </td>
            </tr>
        {% else %}
            <tr><th>No hay calificaciones para la evaluación {{ eval.evaluacion }}. <th></tr>
		{% endif %}
	    {% endfor %}
	</table>
	<br/>
{% endfor %}

src/padres/templates/padres/citas.html
{% extends "padres/base.html" %}
{% load i18n %}

{% block breadcrumb %}
	Citas
{% endblock %}


{% block body %}

{% if not error %}

{% if hijos %}

	{% if citas %}
        <h1>Citas pendientes:</h1>
        {% for c in citas %}
            <div class="cita">
                <strong>Tutor: </strong>{{ c.tutoria.tutor }}
                {{ c.fecha }} {{ c.tutoria.hora|time:"H:i" }} (<a href="?borrar=1&amp;cita_id={{ c.id }}">Borrar</a>)
            </div>
        {% endfor %}
		Exportar a: <a href="{% url padres_icalendar %}">iCalendar</a>
	{% endif %}

	<h1>Elija tutor:</h1>
	{% for i in hijos %}
		<b>{{ i.hijo }} </b> <br>
		Tutor:
		{% if i.tutor %}
			{{ i.tutor.profesor }} <br>
			Horas disponibles en el presente mes: 
			{% if i.fechas %}
				<ul>
				{% for t in i.fechas %}
					<li>
						{% if t.full %}
							{{ t.fecha }} (Esta hora está completa)
						{% else %} {{ t.fecha }}
							<a href="?tutoria_id={{ t.tutoria.id }}&amp;fecha={{ t.fecha.isoformat }}&amp;hijo={{ i.hijo.id }}">
								(Solicitar cita)
							</a>
						{% endif %}
					</li>
				{% endfor %}
				</ul>
			{% else %}
				No se han encontrado tutorías <br/>
			{% endif %}
		{% else %}
			No se ha encontrado tutor <br/>
		{% endif %}
	{% endfor %}
{% else %}
	No consta ningún hijo en la base de datos. Por favor, consulte con la
	secretaría para subsanar este error.
{% endif %}

{% endif %}

{% endblock %}

{% block submenu %}
En esta sección puede consultar las citas que tiene concertadas con los tutores de sus hijos, así como cancelar o solicitar una cita con los mismos.
{% endblock %}

src/padres/templates/padres/faltas_archive_week.html
{% extends "padres/base.html" %}
{% load i18n %}

{% block body %}

<h1>{{ nombreFalta }}</h1>

{% if object_list %}
	{% for f in object_list %}
		{{ f.asignatura }}
	{% endfor %}
{% else %}
	No se le ha asignado ninguna falta
{% endif %}

{% endblock %}

src/padres/templates/padres/login.html
{% extends "padres/base.html" %}
{% load i18n %}
{% block breadcrumb %}Login{% endblock %}
{% block submenu %}{% endblock %}
{% block mainmenu %}{% endblock %}

{% block body %}

	<h1>Inicio de sesión:</h1>

	{% if form.has_errors %}
		<p class="error">Por favor, corrija los siguientes errores:</p>
	{% endif %}

	{% comment %}
	{% if error %}
		<h2>{{ error }}</h2>
	{% endif %}
	{% endcomment %}

	<p class="block">
		Para acceder a la zona privada de este sitio web, por favor, inicie sesión.
	</p>
		<form method="post" action="." class="login">
		<table id="tablaLogin">
		<tr>
		<td>
			<table>
				<tr>
					<td>
						<label for="id_usuario">Usuario:</label>
						
					</td><td>{{ form.usuario }}</td>
				</tr>
				{% if form.usuario.errors %}
				<tr>
					<td colspan="2">
						*** {{ form.usuario.errors|join:", " }}
					</td>
				</tr>
				{% endif %}
				<tr>
					<td>
						<label for="id_usuario">Contraseña:</label>
					</td><td>{{ form.password }}</td>
				</tr>
				{% if form.password.errors %}
				<tr>
					<td colspan="2">
						*** {{ form.password.errors|join:", " }}
					</td>
				</tr>
				{% endif %}
				<tr>
					<td colspan="2" align="center">
						<input type="submit" value="Iniciar sesión"/>
					</td>
				</tr>
			</table>
		</td>
		<td>
				<img src="{{ MEDIA_URL }}/imgs/key.jpg" alt="Login"/>
		</td>
		</tr>
		</table>
		</form>
        <script type="text/javascript">document.getElementById('id_usuario').focus();</script>
{% endblock %}