src/docencia/informes/urls.py
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.conf.urls.defaults import *

urlpatterns = patterns('docencia.informes.views',
    url(r'^resumen_tutor/$',            'resumen_tutor', name = 'resumen_tutor'),
    url(r'^informe_tutor/$',            'informe_tutor', name = 'informe_tutor'),
    url(r'^informe_tutor/(?P<grupo>\d+)/$', 'informe_tutor', name = 'informe_tutor_grupo'),
    url(r'^informe_partes/$',           'informe_partes', name = 'informe_partes'),
    url(r'^informe_personalizado/$',    'informe_personalizado', name = 'informe_personalizado'),
    url(r'^informe_personalizado/(?P<grupo>\d+)/$', 'informe_personalizado', name = 'informe_personalizado_grupo'),
    url(r'^resumenEvaluacionProfesor/$', 'resumenEvaluacionProfesor', {'tipo': 'Profesor'}, name = 'resumen_evaluacion_profesor'),
    url(r'^resumenEvaluacionTutor/$',   'resumenEvaluacionProfesor', {'tipo': 'Tutor'}, name = 'resumen_evaluacion_tutor'),
    url(r'^resumenEvaluacionTutor/(?P<grupo>\d+)/$', 'resumenEvaluacionProfesor', {'tipo': 'Tutor'}, name = 'resumen_evaluacion_tutor_grupo'),
    url(r'^informe_absentismo/$', 'informe_absentismo', name='informe_absentismo'),
)

src/docencia/urls.py
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.conf.urls.defaults import *
from faltas.models import Parte

urlpatterns = patterns('',
    (r'^informes/',     include('docencia.informes.urls')),
    (r'^verificacion/', include('docencia.verificacion.urls')),
)

urlpatterns += patterns('docencia.views',
    url(r'^$',                                      'akademicLogin', name='login'),
    url(r'^error/$',                                'error', name='error'),
    url(r'^menu/(?P<menu>\w+)/$',                   'gestionMenu', name='gestion_menu'),
    url(r'^profesor-index(/(?P<task>\w+)(/(?P<semana_id>\d+))?)?/$', 'profesorIndex', name='profesor_index'),
    url(r'^faltasActual/$',                         'faltas', {'tipo': 'faltas'}, name='profesor_faltas_actual'),
    url(r'^faltasActual/(?P<inserta>\d)/$',         'faltas', {'tipo': 'faltas'}, name='profesor_faltas_inserta'),
    url(r'^faltas/(?P<fecha>\d+-\d+-\d+)/(?P<hora_id>\d+)/$', 'faltas', {'tipo': 'faltas'}, name='profesor_faltas_fecha'),
    url(r'^faltas/(?P<fecha>\d+-\d+-\d+)/(?P<hora_id>\d+)/(?P<inserta>\d)/$', 'faltas', {'tipo': 'faltas'}, name='profesor_faltas_fecha_inserta'),
    url(r'^faltas/(?P<fecha>\d+-\d+-\d+)/$', 'faltas', {'tipo': 'faltas', 'hora_id': None}, name='profesor_faltas_especiales'),
    url(r'^faltas/(?P<fecha>\d+-\d+-\d+)/(?P<inserta>\d)/$', 'faltas', {'tipo': 'faltas', 'hora_id': None}, name='profesor_faltas_especiales_inserta'),
    url(r'^comportamientoActual/$',                 'faltas', {'tipo': 'comportamiento'}, name='profesor_comportamiento_actual'),
    url(r'^comportamiento/(?P<fecha>\d+-\d+-\d+)/(?P<hora_id>\d+)/$', 'faltas', {'tipo': 'comportamiento'}, name='profesor_comportamiento_fecha'),
    url(r'^comportamiento/(?P<fecha>\d+-\d+-\d+)/$', 'faltas', {'tipo': 'comportamiento', 'hora_id': None}, name='profesor_comportamiento_especial'),
    url(r'^insertafaltas/$',                        'insertaFalta', {'tipo': 'faltas'}, name='profesor_inserta_faltas'),
    url(r'^insertacomportamiento/$',                'insertaFalta', {'tipo': 'comportamiento'}, name='profesor_inserta_comportamiento'),
    url(r'^horarioFaltas(/(?P<semana>-?\d+))?/$',   'horarioProfesor', {'tipo': 'faltas'}, name='profesor_horario_faltas'),
    url(r'^horarioComportamiento(/(?P<semana>-?\d+))?/$', 'horarioProfesor', {'tipo': 'comportamiento'}, name='profesor_horario_comportamiento'),
    url(r'^listasTutorAsignaturas/$',               'listasTutorAsignaturas', name='tutor_lista_asignaturas'),
    url(r'^printListasTutorAsignaturas/$',          'listasTutorAsignaturas', name='tutor_print_lista_asignaturas'),
    url(r'^listasTutorTotales/$',                   'listasTutorTotales', name='tutor_lista_totales'),
    url(r'^listadosProfesor/$',                     'listadosProfesor', name='profesor_mostrar_listados'),
    url(r'^Akademic.ics$',                          'getCitasiCalendar', name='get_citas_calendar'),
    url(r'^citas/$',                                'listaCitasProfes', name='profesor_lista_citas'),
    url(r'^citas/(?P<fecha>\d+)/$',                 'detailCitas', name='profesor_detail_citas'),
    url(r'^notificacionSmsProfesor/$',              'notificacionSmsProfesor', name='notificacion_sms_profesor'),
    url(r'^notificacionSmsMasivo/$',                'envio_notificaciones_sms_agrupadas', 
                                                        { 'urlname': 'niveles'}, name='notificacion_sms_masivo'),
    url(r'^notificacionSmsPorCurso/$',              'envio_notificaciones_sms_agrupadas', 
                                                        { 'urlname': 'cursos'}, name='notificacion_sms_curso'),
                                                        
    url(r'^notificacion_sms_grupo/$',               'envio_notificacion_grupo', name='notificacion_sms_grupo'),  
    url(r'^notificacion_sms_grupo/(?P<grupo>\d+)/$', 'envio_notificacion_grupo', name='notificacion_sms_grupo_orientador'),                                  
    url(r'^estadoNotificacion/$',                   'estadoNotificacion', name='estado_notificacion'),
    url(r'^estadoNotificacion/(?P<page>\d+)/$',     'estadoNotificacion', name='estado_notificacion'),    
    url(r'^poseer/$',                               'posesion', name='profesor_posesion'),
    #url(r'^evaluacionProfesor/$',                   'evaluacionProfesor', name='profesor_evaluacion'),
    #url(r'^evaluacionTutor/(?P<tutor>\w+)/$',       'evaluacionProfesor', name='tutor_evaluacion'),
    url(r'^evaluarCompetencias/$',                  'evaluarCompetencias', name='evaluar_competencias'),
    url(r'^nuevaEvaluacion/$',                      'nuevaEvaluacion', name='nueva_evaluacion'),
    url(r'^generarBoletin/$',                       'generarBoletin', name='generar_boletin'),
    url(r'^comentario/$',                           'comentario', name='comentario'),
    url(r'^reenvioPassword/$',                      'reenvioPassword', name='reenvio_password'),

    url(r'^informeNagios/$',                        'informeNagios', name='informe_nagios'),
    url(r'^boletinQT/$',                            'boletinQT', name='boletin_qt'),
    url(r'^grupo/$',                                'selecciona_grupo', name='selecciona_grupo'),
    url(r'^grupo_sms/$',                            'selecciona_grupo_sms', name='selecciona_grupo_sms'),
    url(r'^grupo_je/$',                             'grupo_informe_je', name='selecciona_grupo_je'),
    url(r'^dias_especiales/$',                      'gestion_dias_especiales', name='dias_especiales'),
    url(r'^lista_dias_especiales/$',                'special_days_list', name='lista_dias_especiales'),
    url(r'^eliminar_dia/(?P<dia_id>\d+)/$',         'del_special_day', name='dia_especial_eliminar'),
    url(r'^attach_file/$',                          'attach_file', name='attach_file'),
)

parte_dict = {
    'queryset': Parte.objects.all(),
}

urlpatterns += patterns('django.views.generic.list_detail',
    url(r'^partes/$',                               'object_list', dict(parte_dict, paginate_by=20, allow_empty=True), name='partes'),
    url(r'^partes/page(?P<page>[0-9]+)/$',          'object_list', dict(parte_dict, paginate_by=20, allow_empty=True), name='partes_page'),
    url(r'^parte/(?P<object_id>[0-9]+)/$',          'object_detail', parte_dict, name='parte_object'),
)

src/docencia/verificacion/urls.py
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.conf.urls.defaults import *

urlpatterns = patterns('docencia.verificacion.views',
    url(r'^seleccionaCurso/$',         'seleccionaCurso', name='verificacion_selecciona_curso'),
    url(r'^curso/(?P<grupo_id>\d+)/$', 'verificaCurso', name='verificacion_curso'),
    url(r'^verificados/$',             'verificados', name='verificados'),
    url(r'^desdoble/$',                'desdoble', name='desdoble'),
)

src/urls.py
# -*- encoding: utf-8 -*-
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
import authority

admin.autodiscover()
authority.autodiscover()

if settings.MAINTENANCE:
    akademic_patterns = patterns('',
        (r'^admin/',             include(admin.site.urls)),
        (r'',          'docencia.views.work_in_progress'), 
    )
else:
    akademic_patterns = patterns('',
        (r'^$',                 'docencia.views.akademicLogin'),
        url(r'^accounts/login/$',  'docencia.views.akademicLogin', name='login'),
        url(r'^accounts/logout/$', 'docencia.views.akademicLogout', name='logout'),
        (r'^akademic/',          include('docencia.urls')),
        (r'^admin/',             include(admin.site.urls)),
        (r'^incidencias/',       include('incidencias.urls')),
        (r'^recursos/',          include('recursos.urls')),
        (r'^conector/',          include('conector.urls')),
        (r'^padres/',            include('padres.urls')),
        (r'^pas/',               include('pas.urls')),
        (r'^authority/',         include('authority.urls')),
        # Sólo en modo de desarrollo.
        (r'^site-media/(.*)$',  'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

cleaned_site_location = settings.SITE_LOCATION.lstrip('/')
if cleaned_site_location != "": cleaned_site_location += "/"

urlpatterns = patterns('',
    (cleaned_site_location, include(akademic_patterns)),
)

src/docencia/faltas/models.py
# -*- encoding: utf-8 -*-
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.db import models

from docencia.horarios.models import Hora
from notificacion.constants import ESTADO_NOTIFICACION
from docencia.constants import *

import datetime

class Ausencia(models.Model):
    """
        Representa una ausencia de un alumno (castigo o lo que sea)
    """
    alumno = models.ForeignKey('docencia.Alumno')
    inicio = models.DateTimeField()
    fin = models.DateTimeField(null = True)
    motivo = models.TextField('Motivo de la ausencia', blank = True, null = True)
    notificadoSMS = models.IntegerField('Estado notificacion SMS', choices = ESTADO_NOTIFICACION, default = 3)

    def finaliza (self):
        self.fin = datetime.datetime.now()
        self.save ()
    
    def __unicode__(self):
        return u"%s %s" % (self.alumno.persona.nombre,  self.alumno.persona.apellidos)

    def fechaBonita (self):
        return (self.fecha.strftime ('%a dia %d de %b de %Y'))

class Uniforme(models.Model):
    """
        Representa una falta de uniforme por parte del alumno
    """
    alumno = models.ForeignKey('docencia.Alumno', unique_for_date = 'dia') #Igual que poner unique_together = ['alumno', dia'])
    dia = models.DateField()
 
class Falta(models.Model):
    """
        Representa una falta de asistencia de un alumno.
    """
    alumno = models.ForeignKey('docencia.Alumno')
    fecha = models.DateField()
    hora = models.ForeignKey(Hora)
    asignatura = models.ForeignKey('docencia.Asignatura')
    tipo = models.IntegerField(u'Tipo de falta', choices=TIPO_FALTAS)
    notificadoSMS = models.BooleanField('Falta notificada por SMS')
    textoIncidencia = models.TextField('Texto de la incidencia', blank = True, null = True)
    
    def __unicode__(self):
        return u"%s [%s %s]" % (self.alumno.persona, self.hora, self.asignatura)
    
class Parte(models.Model):
    """
        Almacena cada uno de los envíos de faltas que realiza un determinado
        profesor.
    """
    profesor = models.ForeignKey('docencia.Profesor')
    asignatura = models.ForeignKey('docencia.Asignatura')
    # Fecha de la asignatura
    fecha = models.DateTimeField('Fecha', blank = False)

    def __unicode__(self):
        return u"%s %s %s" % (self.fecha, self.asignatura, self.profesor)

    class Meta:
        ordering = ['-fecha']

class EnviosFaltas(models.Model):
    """
        Almacena la fecha de cada uno de los envíos de faltas que realiza un
        determinado profesor para una asignatura dada.
    """
    parte = models.ForeignKey(Parte)
    # Fecha del envío
    fecha = models.DateTimeField('Fecha', blank = False)
    ip = models.IPAddressField(blank = True, null = True)
    # UserAgent
    user_agent = models.CharField(max_length = 255, blank = True, null = True)

    def __unicode__(self):
        return u"%s %s %s" % (self.fecha, self.ip, self.user_agent)

    class Meta:
        ordering = ['-fecha']

src/docencia/informes/forms.py
# -*- encoding: utf-8 -*-
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django import forms

import datetime
import re

from django.forms.extras.widgets import SelectDateWidget
from django.forms.widgets import Select
from django.utils.dates import MONTHS
from django.utils.safestring import mark_safe


RE_DATE = re.compile(r'(\d{4})-(\d\d?)-(\d\d?)$')

src/docencia/templates/akademic/base.html
<html>
<head>
	<title>{% block maintitle %}Akademic::{% endblock %}</title>
	<link rel="stylesheet" href="{{ MEDIA_URL }}/css/template_css.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="{{ MEDIA_URL }}/css/menu.css" type="text/css" media="screen"/>
	<link rel="stylesheet" href="{{ MEDIA_URL }}/css/akademic.css" type="text/css" />
	<link rel="alternative stylesheet" type="text/css" href="{{ MEDIA_URL }}/css/print.css" media="screen" title="Print Preview" />
	<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/css/print.css" media="print" />
</head>

<body>
<script language="JavaScript" src="{{ MEDIA_URL }}/js/JSCookMenu.js" type="text/javascript"></script>
<script language="JavaScript" src="{{ MEDIA_URL }}/js/ThemeOffice/theme.js" type="text/javascript"></script>

<div class="vistaPrincipal">
	<div id="menu">
	{% block mainmenu %}{% endblock %}
	</div>

	{% if error %}<div class="error">{{ error }}</div>{% endif %}

	{% block body %}{% endblock %}

	{% block footer %}{% endblock %}

</div>
</body>
</html>

src/docencia/templates/akademic/error.html
<html>
<body>
<div style="text-align: center; font-size: 110%; font-weight: bold; padding-top:
10px">
Ha ocurrido un error en la aplicación. Por favor, póngase en contacto con
los administradores para subsanarlo lo antes posible.
</div>
</body>
</html>

src/docencia/templates/akademic/error2.html
{% extends "akademic/padres/base.html" %}
{% load i18n %}

{% block breadcrumb %}Error Fatal{% endblock %}
{% block submenu %}{% endblock %}
{% block mainmenu %}{% endblock %}

{% block body %}

	<h1>Error Fatal</h1>

	{% if msg %}
		<p class="error">{{msg}}</p>
	{% endif %}

{% endblock %}

src/docencia/templates/akademic/evaluacionProfesor.html
{% extends "akademic/profesor-index.html" %}

{% block body %}

{% if not error %}
	<form action="{{ action }}" method="POST">
	<table class="curso" width="100%" cellpadding="0" cellspacing="0">
	<tr>
	<td colspan="6" align="center">
		<b>Evaluación de grupos</b><br/>
		Profesor {{ profesor }} <br/>
	</td>
	</tr>
	<tr>
		<td colspan="3">
			<b>Seleccione la evaluación correspondiente:</b>
		</td>
		<td colspan="3">
			<select name="evaluacion">
				{% for i in listaEvaluaciones %}
					<option label="{{ i.id }}" value="{{ i.id }}">{{ i.nombre }} {{ i.fecha|date:"d-m-Y" }}</option>
				{% endfor %}
			</select>
		</td>

	</tr>
	</table>
	{% if listaAsignaturas %}
		<table class="curso" width="100%" cellpadding="0" cellspacing="0">
		{% for entrada in listaAsignaturas %}
			<tr class="{% cycle par,impar %}">
				<td colspan="5">
					{{ entrada.asignatura.nombreCorto }} - {{ entrada.grupo.curso }}{{ entrada.grupo.seccion }}
				</td>
				<td>
					<input type="checkbox" name="asignaturas" value="{{ entrada.asignatura.id }}@{{ entrada.grupo.id }}"/>
				</td>
			</tr>
		{% endfor %}
		<tr>
			<td colspan="6" align="right">
				<input type="submit" value="Enviar"/>
			</td>
		<tr>
		</table>
	{% endif %}
	</form>

{% endif %}
{% if listados %}
		<form action="{{ action }}" method="POST">
		<input type="hidden" name="evaluacion" value="{{ evaluacion.id }}"/>
		{% for listado in listados %}
			<p><b>Grupo:</b> {{ listado.grupo }}</p>
			<p><b>Asignatura:</b> {{ listado.asignatura.nombreLargo }}</p>
			<p><b>Evaluación:</b> {{ evaluacion.nombre }} {{ evaluacion.fecha|date:"d-m-Y" }} </p>
			<table class="curso">
				<tr>
					<th>Nº</th>
					<th>Alumno:</th>
					<th>Nota</th>
                    {% comment %}
					{% ifequal evaluacion.evaluacionCompetencial False %}
						<th>Concept.</th>
						<th>Proc.</th>
						<th>Actitud.</th>
					{% endifequal %}
                    {% endcomment %}
				</tr>
				{% for alu in listado.alumnos %}
				<tr class="{% cycle par,impar %}">
					<td>
						{{ forloop.counter }}
					</td>
					<td class="alumno">{{ alu.alumno }}</td>
					<td class="dia">
						{% if alu.calificacion %}
							<input type="text" name="{{ alu.alumno.id }}@{{ listado.asignatura.id }}" 
							value="{{ alu.calificacion.nota }}" maxlength="2" size="2"/>

						{% else %}
							<input type="text" name="{{ alu.alumno.id }}@{{ listado.asignatura.id }}" 
							value="" maxlength="2" size="2"/>
						{% endif %}
					</td>
                    {% comment %}
					{% ifequal evaluacion.evaluacionCompetencial False %}
						<td>
							<select name="conceptos">
								{% for nota in notasTextuales %}
									<option label="nota.0" value="{{ alu.alumno.id }}@{{ listado.asignatura.id }}@{{nota.0}}"
										{% if alu.calificacion %}
											{% ifequal alu.calificacion.conceptos nota.0 %}
												selected
											{% endifequal %}
										{% endif %}
									>
											{{nota.1}}
									</option>

								{% endfor %}
							</select>
						</td>
						<td>
							<select name="procedimientos">
								{% for nota in notasTextuales %}
									<option label="nota.0" value="{{ alu.alumno.id }}@{{ listado.asignatura.id }}@{{nota.0}}"
										{% if alu.calificacion %}
											{% ifequal alu.calificacion.procedimientos nota.0 %}
												selected
											{% endifequal %}
										{% endif %}
									>
											{{nota.1}}
									</option>
								{% endfor %}
							</select>
						</td>
						<td>
							<select name="actitud">
								{% for nota in notasTextuales %}
									<option label="nota.0" value="{{ alu.alumno.id }}@{{ listado.asignatura.id }}@{{nota.0}}"
										{% if alu.calificacion %}
											{% ifequal alu.calificacion.actitud nota.0 %}
												selected
											{% endifequal %}
										{% endif %}
									>
											{{nota.1}}
									</option>
								{% endfor %}
							</select>
						</td>

					{% endifequal %}
                    {% endcomment %}
				</tr>
				{% endfor %}
			</table>
		{% endfor %}
		<table class="curso">
				<tr>
					<td colspan="6" align="right">
						<input type="submit" value="Enviar"/>
					</td>
				</tr>
		</table>
		</form>
{% endif %}

{% endblock %}

src/docencia/templates/akademic/formularioMesAnyo.html
	<tr><td colspan="6"><b>Seleccione mes y año</b></td></tr>
	<tr>
		<td colspan="6">
			<select name="fechames">
			{% for i in meses %}
				<option {% ifequal i.0 mesActual %} selected {% endifequal %} label="{{ i.1 }}" value="{{ i.0 }}" >{{ i.1 }}</option>
			{% endfor %}
			</select>
			<select name="fechanyo">
			{% for i in anyos %}
				<option {% ifequal i anyoActual %} selected {% endifequal %} label="{{ i }}" value="{{ i }}" >{{ i }}</option>
			{% endfor %}
			</select>
		</td>
	</tr>

src/docencia/templates/akademic/formularioTipoListado.html
	<tr><td colspan="6"><b>Seleccione el tipo de listado que desea obtener:</b></td></tr>
	<tr>
		<td colspan="6">
			<select name="tipoListado">
			{% for i in tipoListado %}
				<option label="{{ i.1 }}" value="{{ i.0 }}">{{ i.1 }}</option>
			{% endfor %}
			</select>
		</td>
	</tr>

src/docencia/templates/akademic/main-menu.html
<table class="menu">
	<tr>
		<td id="menuSubir">
			<a href="{% url gestion_menu 'menu' %}">
				<img src="{{ MEDIA_URL }}/imgs/menu.png"/>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Volver al menú&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			</a>
		</td>
	</tr>
</table>

src/docencia/templates/akademic/parte_detail.html
{% extends "akademic/profesor-index.html" %}

{% block body %}

{% if not error %}
	<table class="curso" width="100%" cellpadding="0" cellspacing="0">
	<tr>
		<th align="center">Detalle del parte</th>
	</tr>
	<tr>
		<td>
			Fecha y hora de la clase: {{ object.fecha }}<br/>
			Profesor: {{ object.profesor }}<br/>
			Asignatura: {{ object.asignatura }}<br/>
		</td>
	</tr>
	</table>
	<br/>
	<table class="curso" width="100%" cellpadding="0" cellspacing="0">
	<tr>
		<th colspan=3 align="center">Detalle de los envíos</th>
	</tr>
	<tr>
		<th align="center">Fecha</th>
		<th align="center">IP origen</th>
		<th align="center">Navegador</th>
	</tr>
	{% for i in object.enviosfaltas_set.all %}
	<tr class="{% cycle par,impar %}">
		<td align="center">{{ i.fecha }}</td>
		<td align="center">{{ i.ip }}</td>
		<td align="center">{{ i.ua }}</td>
	</tr>
	{% endfor %}
	</table>
{% endif %}

{% endblock %}