src/recursos/urls.py
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.conf.urls.defaults import *
from recursos.models import *
from django.db.models import Q

urlpatterns = patterns('recursos.views',
    url(r'^$',                                      'index',        name="recursos_raiz"),
    url(r'^lista/(?P<tipo_recurso>\w+)/',           'listatipo',    name="lista_recursos"),
    url(r'^lista/',                                 'listatipo',    name="lista_recursos"),
    url(r'^reservas/eliminar/(?P<reserva_id>\w+)/', 'eliminarReserva', name="eliminar_reserva"),
    url(r'^reservas/(?P<tipo_recurso>\w+)/',        'reservas',     name="lista_reservas"),
    url(r'^reservas/',                              'reservas',     name="lista_reservas"),
    url(r'^nuevareserva/(?P<recurso_id>\w+)/',      'nuevaReserva', name="nueva_reserva"),
    url(r'^nuevo_recurso/',                         'nuevo_recurso', name="nuevo_recurso"),
)

src/urls.py
# -*- encoding: utf-8 -*-
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
import authority

admin.autodiscover()
authority.autodiscover()

if settings.MAINTENANCE:
    akademic_patterns = patterns('',
        (r'^admin/',             include(admin.site.urls)),
        (r'',          'docencia.views.work_in_progress'), 
    )
else:
    akademic_patterns = patterns('',
        (r'^$',                 'docencia.views.akademicLogin'),
        url(r'^accounts/login/$',  'docencia.views.akademicLogin', name='login'),
        url(r'^accounts/logout/$', 'docencia.views.akademicLogout', name='logout'),
        (r'^akademic/',          include('docencia.urls')),
        (r'^admin/',             include(admin.site.urls)),
        (r'^incidencias/',       include('incidencias.urls')),
        (r'^recursos/',          include('recursos.urls')),
        (r'^conector/',          include('conector.urls')),
        (r'^padres/',            include('padres.urls')),
        (r'^pas/',               include('pas.urls')),
        (r'^authority/',         include('authority.urls')),
        # Sólo en modo de desarrollo.
        (r'^site-media/(.*)$',  'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

cleaned_site_location = settings.SITE_LOCATION.lstrip('/')
if cleaned_site_location != "": cleaned_site_location += "/"

urlpatterns = patterns('',
    (cleaned_site_location, include(akademic_patterns)),
)

src/recursos/models.py
# -*- encoding: utf-8 -*-
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
import time, datetime

# Create your models here.

TIPOS_DE_RECURSO = (
        (1, 'Aulas'),
        (2, 'Material deportivo'),
        (3, 'Audiovisuales'),
        (4, 'Otros'),
    )

class Recurso (models.Model):
    """
        Define uno de los recursos que pueden soliticar los profesores
    """
    descripcion = models.CharField ('Descripción', max_length= 255, blank = False, null = False)
    tipo = models.IntegerField ('Tipo', choices = TIPOS_DE_RECURSO, null = False)
    actualmenteDisponible = models.BooleanField ('Disponible', null = False)

    def __unicode__(self):
        return u"%s - %s" % (self.descripcion, self.get_tipo_display())

    @staticmethod
    def getDisponibles (tipo_recurso = None):
            if tipo_recurso is None:
                return Recurso.objects.filter(Q(actualmenteDisponible = True))
            else:
                return Recurso.objects.filter(
                        Q(actualmenteDisponible = True) & 
                        Q(tipo = tipo_recurso)
                    )



class Reserva (models.Model):
    """
        Define la reserva de un recurso por un profesor
    """
    recurso = models.ForeignKey (Recurso, null = False)
    responsable = models.ForeignKey (User, null = False)
    motivo = models.TextField ('Motivo de la reserva', blank = False, null = False)
    inicio = models.DateTimeField (null = False)
    fin = models.DateTimeField (null = False)

    def __unicode__(self):
        return u"%s %s (%s - %s)" % (self.recurso, self.responsable, self.inicio, self.fin)

    @staticmethod
    def getReservas (recurso_id = None, tipo = None, usuarioResponsable = None):
        """
            Devuelve las reservas que hay sobre este en el futuro
        """
        filtro = None
        if tipo is not None:
            filtro = Q(recurso__tipo = tipo)
    
        if usuarioResponsable is not None:
            if filtro is not None:
                filtro &= Q(responsable = usuarioResponsable)
            else:
                filtro = Q(responsable = usuarioResponsable)
    
        if recurso_id is not None:
            if filtro is not None:
                filtro &= Q(recurso = recurso_id)
            else:
                filtro = Q(recurso = recurso_id)
        if filtro is not None:
            filtro &= Q(fin__gte = time.strftime ('%Y-%m-%d %H:%M:%S'))
        else:
            filtro = Q(fin__gte = time.strftime ('%Y-%m-%d %H:%M:%S'))
    
        return Reserva.objects.filter(filtro).order_by ('inicio')

    @staticmethod
    def getCalendario (setDictFunction = None, diccionarioAdicional = None, semana = None, anyo = None):
        """
            devuelve una estructura con la información de las reservas de una semana
        """
        if not anyo:
            anyo = time.strftime("%Y")
        if not semana:
            semana = time.strftime("%W")

        anyoNuevo = datetime.datetime(int(anyo), 1, 1)

        diasAnyo = datetime.timedelta(weeks = int(semana))

        anyoNuevoWD = datetime.timedelta(days = anyoNuevo.weekday())

        #lunes = datetime.timedelta(days = 6)
        aux = fecha = anyoNuevo + diasAnyo - anyoNuevoWD
        dias_semana = []

        #Encabezado de la tabla
        dias_semana.append([{'texto':'Horas', 'class': 'header'}])
        for i in range(5):
            dias_semana.append([{'texto':aux.strftime('%d-%m-%y'), 'class': 'header'}])
            aux = aux + datetime.timedelta(days = 1)

        # Lista de horas, desde las 8 de la mañana a las 8 de la tarde
        aux = datetime.datetime(int(anyo), 1, 1)
        aux = aux + datetime.timedelta (hours = 7, minutes = 30)
        for i in range(24):
            aux = aux + datetime.timedelta (minutes = 30)
            dias_semana[0].append({'texto': aux.strftime ('%H:%M'), 'class' : 'header'})
        for j in range(1, 6):
            # Vamos a sacar el día de hoy.
            aux = fecha + datetime.timedelta (hours = 7, minutes = 30, days = j - 1)
            reserva = None
            for i in range(24):
                aux = aux + datetime.timedelta (minutes = 30)
                if setDictFunction is not None:
                    dias_semana[j].append(setDictFunction (aux, diccionarioAdicional))
                    # el diccionario adicional contiene parámetros que tb se tiene que pasar a este método,
                    # por ejemplo el recurso_id
        #Ahora esta super matriz tendremos que recodificarla porque para poder pintar en html
        #necesitamos la información dispuesta por columnas y no por filas.
        calendario_final = []
        for i in range(25):
            fila = []
            hora = dias_semana[0][i]['texto']
            for j in range(6):
                fila.append (dias_semana[j][i])
#               if dias_semana[j][i]['class'] == 'ocupado':
            calendario_final.append(fila)
#       return dias_semana
        return calendario_final

def setDictRecurso (datetime, diccionario):
    # Debería pillar el día y la hora y buscar reservas del recurso tal que inicio <= tiempo y fin >= tiempo
    try:
        reserva = Reserva.objects.get (
                Q(inicio__lte = datetime) &
                Q(fin__gt = datetime) &
                Q(recurso = diccionario['recurso_id'])
            )
        return ({'texto': reserva.responsable, 'class': 'ocupado'})
    except Reserva.DoesNotExist:
        return ({'texto': ' ', 'class': 'libre'})

src/recursos/forms.py
"""
    Akademic: Herramienta para el control del alumnado en centros escolares.

    Copyright (C) 2010  Galotecnia Redes Sistemas y Servicios S.L.L. <info@galotecnia.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from django import forms
from models import Reserva, Recurso

class ReservaForm(forms.ModelForm):

    class Meta:
        model = Reserva
        exclude = ['id']

class RecursoForm(forms.ModelForm):
        
    class Meta:
        model = Recurso
        exclude = ['id']

    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        self.fields['actualmenteDisponible'].initial = True

src/recursos/templates/recursos/richWebBrowser/confirma-borrado.html
{% extends "recursos/richWebBrowser/menu/recursos.html" %}

{% block breadcrumb %}Recursos >> Eliminar Reserva{% endblock %}

{% block body %}
	<b>¿Esta segro de que quiere eliminar esta reserva?</b>
	{% include 'recursos/bloque-reserva.html' %}
	<form action="" method="post">
		<input type="submit" name="aceptar" value="Si"/>
		<input type="submit" name="cancelar" value="No"/>
	</form>
{% endblock %}

src/recursos/templates/recursos/richWebBrowser/index.html
{% extends "recursos/richWebBrowser/menu/recursos.html" %}

{% block breadcrumb %}Recursos >> Inicio{% endblock %}

{% block body %}
	<div class="aviso"><h1>Sistema de gestión de recursos de Akademic2</h1></div>
	<p>
		Utilice los enlaces que se disponen en la parte superior de
		este sitio web para acceder a la información de los recursos y sus reservas.
	</p>
{% endblock %}

src/recursos/templates/recursos/richWebBrowser/nueva-reserva.html
{% extends "recursos/richWebBrowser/menu/recursos.html" %}

{% block breadcrumb %}Recursos >> Nueva Reserva{% endblock %}

{% block body %}
	{% if errors.colision %}
	<h1>{{ errors.colision }}</h1>
	{% for reserva in errors.reservas_previas %}
		{% include 'recursos/bloque-reserva.html' %}
	{% endfor %}

	{% endif %}
<form action="" method="post">
	<input type="hidden" name="recurso" value="{{ recurso_id }}"/>
	<fieldset>
		<legend>Nueva reserva:</legend>
		<label for="id_motivo">Motivo:</label>{{ form.motivo }}
			{% if form.motivo.errors %}
				*** {{ form.motivo.errors|join:", " }}
			{% endif %}
			<br/>
		<label for="fechaidia">Fecha inicial:</label>
			<select name="fechaidia">
			{% for i in diasMes %}
				<option {% ifequal i diaActual %} selected {% endifequal %} label="{{ i }}" value="{{ i }}">{{ i }}</option>
			{% endfor %}
			</select>
			<select name="fechaimes">
			{% for i in meses %}
				<option {% ifequal i.0 mesActual %} selected {% endifequal %} label="{{ i.1 }}" value="{{ i.0 }}">{{ i.1 }}</option>
			{% endfor %}
			</select>
			<select name="fechaianyo">
			{% for i in anyos %}
				<option {% ifequal i anyoActual %} selected {% endifequal %} label="{{ i }}" value="{{ i }}">{{ i }}</option>
			{% endfor %}
			</select>
			<br/>
		<label for="inicio_time">Hora de inicio:</label>
			<select name="inicio_time">
			{% for h in horas%}
				<option label="{{ h }}" value="{{ h }}">{{ h }}</option>
			{% endfor %}
			</select>
			{% if form.inicio_date.errors %}
				*** {{ form.inicio_date.errors|join:", " }}
			{% endif %}
			{% if form.inicio_time.errors %}
				*** {{ form.inicio_time.errors|join:", " }}
			{% endif %}
			<br/>
		<label for="fin_time">Hora de fin:</label>
			<select name="fin_time">
			{% for h in horas%}
				<option label="{{ h }}" value="{{ h }}">{{ h }}</option>
			{% endfor %}
			</select>
			{% if form.fin_date.errors %}
				*** {{ form.fin_date.errors|join:", " }}
			{% endif %}
			{% if form.fin_time.errors %}
				*** {{ form.fin_time.errors|join:", " }}
			{% endif %}
			<br/>
		<label for="submit"></label><input type="submit" value="reservar"/>
	</fieldset>
</form>

	<h1>Lista de reservas sobre este recurso:</h1>
	{% for reserva in reservas %}
		<hr/>
		{% include 'recursos/bloque-reserva.html' %}
	{% endfor %}
<h1>Calendario de reservas</h1>
<div id="menuTiposIncidencia">
	<a href="?semana={{ semanaAnterior }}">Semana anterior</a> |
	<a href="?semana={{ semanaSiguiente }}">Semana siguiente</a>
</div>
<table id="horarioRecursos" cellpadding="0" cellspacing="0">
	{% for fila in calendario %}
	<tr>
		{% for columna in fila %}
		<td class="{{ columna.class }}">{{ columna.texto }}</td>
		{% endfor %}
	</tr>
	{% endfor %}
</table>



{% endblock %}

src/recursos/templates/recursos/richWebBrowser/nuevo_recurso.html
{% extends "recursos/richWebBrowser/menu/recursos.html" %}

{% block breadcrumb %}Recursos >> Nuevo recurso{% endblock %}

{% block submenu %}
	{{ block.super }}
{% endblock %}

{% block body %}
    {% if msg %}
        <p><b>{{ msg }}</b></p>
    {% endif %}
    <h1>Crear un nuevo recurso</h1>
    <form action="." method="POST">
        <fieldset>
            {{ form.as_p }}
        </fieldset>
        <input type="submit" class="button" value="Crear"/>
    </form>
{% endblock %}

src/recursos/templates/recursos/richWebBrowser/recursos_list.html
{% extends "recursos/richWebBrowser/menu/recursos.html" %}

{% block breadcrumb %}Recursos >> Lista de recursos{% endblock %}

{% block submenu %}
	{% for tipo in TIPOS_DE_RECURSO %}
		<li>- <a href="{% url lista_recursos tipo.0 %}">{{ tipo.1 }}</a></li>
	{% endfor %}
	{{ block.super }}
{% endblock %}

{% block body %}
    {% if object_list %}
        <h1>Lista de recursos disponibles actualmente</h1>
        <table align="center" class="curso" cellpadding="0" cellspacing="0">
            <tr>
                <th>Recurso</th>
                <th>Tipo</th>
                <th>Acción</th>
            </tr>
            {% for recurso in object_list %}
            <tr class="{% cycle impar,par %}">
                <td>{{ recurso }}</td>
                <td>{{ recurso.get_tipo_display }}</td>
                <td><a href="{% url nueva_reserva recurso.id %}">Reservar</a></td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h1>No existen recursos disponibles actualmente</h1>
    {% endif %}
{% endblock %}

src/recursos/templates/recursos/richWebBrowser/reservas.html
{% extends "recursos/richWebBrowser/menu/recursos.html" %}

{% block breadcrumb %}Recursos >> Lista de recursos{% endblock %}

{% block submenu %}
	{% for tipo in TIPOS_DE_RECURSO %}
		<li>- <a href="{% url lista_reservas tipo.0 %}">{{ tipo.1 }}</a></li>
	{% endfor %}
	{{ block.super }}
{% endblock %}

{% block body %}
    {% if object_list %}
        <h1>Lista de reservas</h1>
        {% for reserva in object_list %}
            <hr/>
            {% include 'recursos/bloque-reserva.html' %}
        {% endfor %}
    {% else %}
        <h1>Actualmente no existe ninguna reserva</h1>
    {% endif %}
{% endblock %}